gohook:
  image: begizi/gohook-server
  environment:
    - MONGO_URL=mongo
    - "REDIS_ADDR=redis:6379"
  ports:
    - "8080:8080"
    - "9001:9001"
  links:
    - mongo
    - redis
redis:
  image: redis
  ports:
    - "6379:6379"
mongo:
    image: mongo
    ports:
        - "27017:27017"
