# gohook:
#   image: gohookd
#   environment:
#     - MONGO_URL=mongo
#   ports:
#     - "8080:8080"
#     - "9001:9001"
#   links:
#     - mongo
redis:
  image: redis
  ports:
    - "6379:6379"
mongo:
    image: mongo
    ports:
        - "27017:27017"
