apiVersion: v1
kind: Service
metadata:
  name: gohook
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    name: api
  - port: 9001
    protocol: TCP
    name: grpc
  selector:
    version: alpha
    tier: backend
