apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gohook
spec:
  replicas: 1
  template:
    metadata:
      labels:
        tier: backend
    spec:
      containers:
      - name: gohook-server
        image: gcr.io/gohook-io/gohook-server:1.0.0
        env:
        - name: MONGO_URL
          value: mongo
        - name: HTTP_ORIGIN
          value: gohook.io
        ports:
        - containerPort: 8080
        - containerPort: 9001
