apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: redis
  name: redis-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: redis
    spec:
      containers:
      - name: redis
        image: redis:3.0.6
        ports:
        - containerPort: 6379
